package com.foundway.send.smsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SmsServiceSoap", targetNamespace = "http://www.foundway.com/send/smsservice")
public interface SmsServiceSoap {

	/**
	 * 
	 * @param level
	 * @param shortNumber
	 * @param timeStamp
	 * @param hashedPwd
	 * @param message
	 * @param address
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Send", action = "send")
	@WebResult(name = "SendResult", targetNamespace = "http://www.foundway.com/send/smsservice")
	@RequestWrapper(localName = "Send", targetNamespace = "http://www.foundway.com/send/smsservice", className = "com.foundway.send.smsservice.Send")
	@ResponseWrapper(localName = "SendResponse", targetNamespace = "http://www.foundway.com/send/smsservice", className = "com.foundway.send.smsservice.SendResponse")
	public String send(
			@WebParam(name = "shortNumber", targetNamespace = "http://www.foundway.com/send/smsservice")
			String shortNumber,
			@WebParam(name = "timeStamp", targetNamespace = "http://www.foundway.com/send/smsservice")
			String timeStamp,
			@WebParam(name = "hashedPwd", targetNamespace = "http://www.foundway.com/send/smsservice")
			String hashedPwd,
			@WebParam(name = "message", targetNamespace = "http://www.foundway.com/send/smsservice")
			String message,
			@WebParam(name = "address", targetNamespace = "http://www.foundway.com/send/smsservice")
			String address,
			@WebParam(name = "level", targetNamespace = "http://www.foundway.com/send/smsservice")
			PriorityLevel level);

}
